# Generated by Django 2.2.5 on 2019-11-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_ordered',
        ),
    ]
