# Generated by Django 2.2.1 on 2019-06-13 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20190609_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='c_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='c_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='c_title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='c_total_items',
        ),
        migrations.RemoveField(
            model_name='products',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='icon',
        ),
        migrations.AlterField(
            model_name='products',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='products.Products')),
            ],
        ),
    ]
