# Generated by Django 2.2.5 on 2019-11-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190613_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='total_items',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
