# Generated by Django 2.2.5 on 2019-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191130_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='Sports', max_length=50),
            preserve_default=False,
        ),
    ]
